name: Auto Merge By Label Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          gh --version

      - name: Check PR Labels and Auto Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PR 정보 가져오기
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          echo "Checking PR #${PR_NUMBER} in repository ${REPO}"

          # PR에 붙은 라벨 확인
          LABELS=$(gh pr view $PR_NUMBER --repo $REPO --json labels -q '.labels[].name')

          if echo "$LABELS" | grep -q "finished-reviewed"; then
            echo "PR #${PR_NUMBER} has the 'finished-reviewed' label. Proceeding with merge."
            gh pr merge $PR_NUMBER --repo $REPO --admin --squash --body "This PR was auto-merged by GitHub Actions." --subject "Auto-Merged By Action"
          else
            echo "PR #${PR_NUMBER} does not have the 'finished-reviewed' label. Skipping merge."
          fi
