name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: assign developer
        if: ${{ github.event.action=='opened' }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          gh pr $PR_NUMBER edit --repo $REPO --add-assignee "@me"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
              

      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          MERGE_LABELS: "good-to-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Merged by automerge-action"
          MERGE_REQUIRED_APPROVALS: 1
